spring.application.name=EMT-Lab

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.profiles.active=dev

app.jwt.secret=VGhpc0lzQVN0cm9uZ0Rldk9ubHlKV1RTZWNyZXRLZXlGb3JFTVRMYWIxMjM0NTY=
app.jwt.expiration-ms=3600000

app.auth.seed.enabled=true
app.auth.seed.username=admin
app.auth.seed.password=admin123

