CREATE TABLE author
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name       VARCHAR(255),
    surname    VARCHAR(255),
    country_id BIGINT,
    CONSTRAINT pk_author PRIMARY KEY (id)
);

CREATE TABLE book
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name             VARCHAR(255),
    category         VARCHAR(255),
    author_id        BIGINT,
    state            VARCHAR(255),
    available_copies INTEGER,
    CONSTRAINT pk_book PRIMARY KEY (id)
);

CREATE TABLE country
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    continent VARCHAR(255),
    CONSTRAINT pk_country PRIMARY KEY (id)
);

ALTER TABLE author
    ADD CONSTRAINT FK_AUTHOR_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES country (id);

ALTER TABLE book
    ADD CONSTRAINT FK_BOOK_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES author (id);