CREATE TABLE activity_log
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_name  VARCHAR(255)                NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_type VARCHAR(50)                 NOT NULL
);
